### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by Ro97-vangnooru** [kunalrdeshmukh/End-to-end-compression#1]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Roja\\Desktop\\Newfolder1\\End-to-end-compression-master\\data\\cifar-10-batches-pytrain/'    i have dataset that dataset is not supporting please provide readme file

**Comment by kunalrdeshmukh** [comment]
Hi. I had this dataset on my drive. unfortunately, I lost it.
